# Generated by Django 4.2.1 on 2023-06-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_obra_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='image',
            new_name='imagen',
        ),
    ]
